"""
Entry signal engines for the IHSG swing trading system.

Three independent engines, each with a consistent interface:
  engine.scan(df, ticker, regime) -> EntrySignal | None

Engine priority (highest to lowest):
  1. FVG Pullback        (priority 3) — pullback into Fair Value Gap
  2. Momentum Breakout   (priority 2) — breakout from tight range
  3. Buying on Weakness   (priority 1) — capitulation reversal
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from config.settings import (
    ATR_PERIOD,
    BOW_BOLLINGER_PERIOD,
    BOW_BOLLINGER_STD,
    BOW_MACD_DIVERGENCE_LOOKBACK,
    BOW_MACD_FAST,
    BOW_MACD_SIGNAL,
    BOW_MACD_SLOW,
    BOW_RSI_THRESHOLD,
    BOW_STOCH_RSI_OVERSOLD,
    BOW_STOCH_RSI_PERIOD,
    BOW_VOLUME_CLIMAX_RATIO,
    BREAKOUT_MAX_SPREAD_PCT,
    BREAKOUT_CONSOLIDATION_DAYS,
    BREAKOUT_VOLUME_THRESHOLD,
    BREAKOUT_VOLUME_SPIKE_MIN,
    CONSOLIDATION_MIN_DAYS,
    CONSOLIDATION_MAX_DAYS,
    EMA_CROSSOVER_RSI_MAX,
    EMA_CROSSOVER_RSI_MIN,
    EMA_CROSSOVER_VOLUME_THRESHOLD,
    EMA_FAST_PERIOD,
    EMA_SLOW_PERIOD,
    FVG_LOW_VOLUME_RATIO,
    QST_EMA_PERIOD,
    QST_RSI_CROSS_LEVEL,
    QST_RSI_PERIOD,
    QST_VOLUME_LOOKBACK,
    QST_VOLUME_THRESHOLD,
    REGIME_SMA_SHORT,
    VCLR_CLOSING_RANGE_MAX,
    VCLR_MIN_BODY_PCT,
    VCLR_VOLUME_RATIO,
    VCP_VOLUME_DRYUP_RATIO,
    VCP_DRYUP_DAYS,
    WYCKOFF_SPRING_LOOKBACK,
    WYCKOFF_SPRING_VOLUME_RATIO,
)
from core.indicators import (
    atr,
    bollinger_bands,
    closing_range,
    detect_fvg,
    ema,
    macd,
    rsi,
    sma,
    stoch_rsi,
    volume_ratio,
)
from core.regime import RegimeSnapshot

# Import conditionally to avoid circular imports at module level
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from core.adaptive import StockProfile

logger = logging.getLogger(__name__)


# ─── Data Structures ─────────────────────────────────────────────────────────


@dataclass
class EntrySignal:
    """A concrete buy signal generated by an engine."""

    engine: str  # engine name identifier
    ticker: str
    price: float
    score: float  # ranking score (priority * volume_ratio)
    priority: int  # engine priority (3=highest, 1=lowest)
    details: dict = field(default_factory=dict)

    def __str__(self) -> str:
        return (
            f"[{self.engine}] {self.ticker} @ {self.price:,.0f} "
            f"score={self.score:.2f}"
        )


# ─── Base Engine ─────────────────────────────────────────────────────────────


class BaseEngine(ABC):
    """Abstract base for all entry engines."""

    name: str = "base"
    priority: int = 0

    @abstractmethod
    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        """
        Evaluate a single stock for entry signals.

        Parameters
        ----------
        df : pd.DataFrame
            OHLCV data with DatetimeIndex.
        ticker : str
            Ticker code.
        regime : RegimeSnapshot
            Current market regime state.
        profile : StockProfile | None
            Adaptive per-stock profile. If provided, uses stock-specific
            thresholds instead of global defaults.

        Returns
        -------
        EntrySignal | None
            Signal if triggered, else None.
        """
        ...


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 1: FVG PULLBACK
# ══════════════════════════════════════════════════════════════════════════════


class FVGPullbackEngine(BaseEngine):
    """
    Fair Value Gap Pullback Entry Engine.

    Identifies a 3-candle bullish FVG in an uptrend, then triggers
    a buy when price drops into the FVG zone on low volume and
    prints a higher daily close.

    Conditions:
    1. Stock must be in an uptrend (price > SMA50)
    2. A recent unfilled bullish FVG must exist
    3. Previous day's low penetrated or touched the FVG zone
    4. Volume on the pullback day was below average (< 80%)
    5. Today's close is higher than previous close (reversal)

    Priority: 3 (highest)
    Allowed regimes: BULL, CAUTION
    """

    name = "fvg_pullback"
    priority = 3

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        # Regime gate
        if not regime.allows_engine(self.name):
            return None

        if len(df) < max(REGIME_SMA_SHORT + 10, 60):
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        prev_close = float(prev["Close"])
        prev_low = float(prev["Low"])
        last_open = float(last["Open"])

        # 1. Uptrend check: price above SMA(50)
        sma50 = sma(df["Close"], REGIME_SMA_SHORT)
        if pd.isna(sma50.iloc[-1]) or last_close <= float(sma50.iloc[-1]):
            return None

        # 2. Find recent unfilled bullish FVGs (last 90 calendar days)
        fvgs = detect_fvg(df)
        recent_bullish = [
            g for g in fvgs
            if g.gap_type == "bullish"
            and not g.filled
            and (df.index[-1] - g.date).days <= 90
        ]

        if not recent_bullish:
            return None

        # 3. Volume must be below average on the pullback (previous day)
        vol_ratio = volume_ratio(df, period=20)
        prev_vol_ratio = float(vol_ratio.iloc[-2]) if not pd.isna(vol_ratio.iloc[-2]) else 1.0

        # 4. Check each FVG for a pullback entry
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        for gap in recent_bullish:
            # Previous day's low penetrated or touched the FVG zone
            if prev_low <= gap.gap_high:
                # Low volume on pullback day
                if prev_vol_ratio < FVG_LOW_VOLUME_RATIO:
                    # Today's close is higher (reversal confirmation)
                    if last_close > prev_close and last_close > last_open:
                        last_vol_ratio = float(vol_ratio.iloc[-1]) if not pd.isna(vol_ratio.iloc[-1]) else 1.0
                        score = self.priority * max(last_vol_ratio, 1.0)

                        return EntrySignal(
                            engine=self.name,
                            ticker=ticker,
                            price=round(last_close, 2),
                            score=round(score, 2),
                            priority=self.priority,
                            details={
                                "fvg_date": gap.date.strftime("%Y-%m-%d"),
                                "gap_high": round(gap.gap_high, 2),
                                "gap_low": round(gap.gap_low, 2),
                                "gap_size": round(gap.gap_size, 2),
                                "pullback_vol_ratio": round(prev_vol_ratio, 2),
                                "reversal_vol_ratio": round(last_vol_ratio, 2),
                                "atr": round(last_atr, 2),
                                "sma50": round(float(sma50.iloc[-1]), 2),
                            },
                        )

        return None


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 2: MOMENTUM BREAKOUT
# ══════════════════════════════════════════════════════════════════════════════


class MomentumBreakoutEngine(BaseEngine):
    """
    Momentum Breakout Entry Engine (Minervini VCP Enhanced).

    Identifies tight Volatility Contraction Pattern (VCP) consolidation,
    then triggers a buy on a daily close above the consolidation high
    with strict volume and timing confirmation.

    Minervini VCP Conditions:
    1. Consolidation spread <= adaptive % of price
    2. Today's close must be above the consolidation high
    3. Volume Contraction: last 5 days of base must show volume dryup
       (<70% of 20-day average) — confirms supply exhaustion
    4. Breakout Volume Spike: breakout day volume >= 250% of 20-day
       average — confirms institutional participation
    5. Time Compression Filter: base must span 15-325 trading days
       (3 weeks to 65 weeks). Rejects V-shaped recoveries that lack
       proper "handle" formation.

    Priority: 2
    Allowed regimes: BULL only
    """

    name = "momentum_breakout"
    priority = 2

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        # Regime gate
        if not regime.allows_engine(self.name):
            return None

        if len(df) < BREAKOUT_CONSOLIDATION_DAYS + 5:
            return None

        last = df.iloc[-1]
        last_close = float(last["Close"])

        # Get the 20-day window BEFORE today
        lookback = df.iloc[-(BREAKOUT_CONSOLIDATION_DAYS + 1):-1]

        if len(lookback) < BREAKOUT_CONSOLIDATION_DAYS:
            return None

        # Adaptive threshold: use stock's typical range if profile available
        max_spread = profile.typical_range_pct if profile else BREAKOUT_MAX_SPREAD_PCT
        vol_threshold = BREAKOUT_VOLUME_THRESHOLD
        if profile:
            vol_threshold = max(1.2, profile.volume_spike_threshold * 0.7)

        # 1. Tight consolidation: max spread <= adaptive threshold
        highest = lookback["High"].max()
        lowest = lookback["Low"].min()
        spread_pct = ((highest - lowest) / last_close) * 100.0

        if spread_pct > max_spread:
            return None

        # 2. Close above 20-day high
        high_20d = float(lookback["High"].max())
        if last_close <= high_20d:
            return None

        # ── Minervini Filter A: Volume Contraction (VCP Dryup) ────────
        # The last N days of the consolidation must show volume drying up
        # (below the dryup ratio of the 20-day average) — confirms that
        # sellers have been exhausted in the tightest phase of the base.
        vol_ratio_series = volume_ratio(df, period=20)
        dryup_window = vol_ratio_series.iloc[-(VCP_DRYUP_DAYS + 1):-1]
        if len(dryup_window) >= VCP_DRYUP_DAYS:
            avg_dryup_ratio = float(dryup_window.mean())
            if avg_dryup_ratio >= VCP_VOLUME_DRYUP_RATIO:
                logger.debug(
                    "[%s] VCP rejected: avg volume in last %d days = %.2fx "
                    "(need < %.2fx for dryup)",
                    ticker, VCP_DRYUP_DAYS, avg_dryup_ratio,
                    VCP_VOLUME_DRYUP_RATIO,
                )
                return None

        # ── Minervini Filter B: Breakout Volume Spike ─────────────────
        # The breakout day must have a massive volume spike (>= 250% avg)
        # to confirm institutional participation. Low-volume breakouts
        # are rejected as "whipsaws".
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        # Apply the stricter of adaptive threshold and Minervini spike minimum
        effective_vol_threshold = max(vol_threshold, BREAKOUT_VOLUME_SPIKE_MIN)

        if last_vol_ratio < effective_vol_threshold:
            logger.debug(
                "[%s] Breakout rejected: volume ratio %.2fx < required %.2fx spike",
                ticker, last_vol_ratio, effective_vol_threshold,
            )
            return None

        # ── Minervini Filter C: Time Compression ─────────────────────
        # A proper consolidation base must take TIME (not a V-shape).
        # Find how many days the stock has been in this consolidation range
        # by counting backwards from today how many days price stayed
        # within the consolidation band.
        consolidation_duration = 0
        for i in range(2, min(len(df), CONSOLIDATION_MAX_DAYS + 10)):
            bar = df.iloc[-(i + 1)]
            bar_high = float(bar["High"])
            bar_low = float(bar["Low"])
            # If this bar's range is within the consolidation band, count it
            if bar_low >= lowest * 0.98 and bar_high <= highest * 1.02:
                consolidation_duration += 1
            else:
                break  # Exited the consolidation zone

        if consolidation_duration < CONSOLIDATION_MIN_DAYS:
            logger.debug(
                "[%s] Time compression rejected: base duration %d days "
                "< minimum %d days (V-shape recovery)",
                ticker, consolidation_duration, CONSOLIDATION_MIN_DAYS,
            )
            return None

        if consolidation_duration > CONSOLIDATION_MAX_DAYS:
            logger.debug(
                "[%s] Base too extended: %d days > maximum %d days",
                ticker, consolidation_duration, CONSOLIDATION_MAX_DAYS,
            )
            return None

        # Signal confirmed — all Minervini VCP filters passed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        score = self.priority * last_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "consolidation_days": consolidation_duration,
                "spread_pct": round(spread_pct, 2),
                "high_20d": round(high_20d, 2),
                "breakout_pct": round(((last_close - high_20d) / high_20d) * 100, 2),
                "volume_ratio": round(last_vol_ratio, 2),
                "vcp_dryup_avg": round(avg_dryup_ratio, 2) if len(dryup_window) >= VCP_DRYUP_DAYS else None,
                "atr": round(last_atr, 2),
            },
        )


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 3: BUYING ON WEAKNESS (B.O.W.)
# ══════════════════════════════════════════════════════════════════════════════


class BuyingOnWeaknessEngine(BaseEngine):
    """
    Buying on Weakness (B.O.W.) Entry Engine.

    Identifies extreme capitulation and triggers a buy on a
    bullish reversal candle with massive volume.

    Capitulation conditions (one or both):
    - Price < Lower Bollinger Band (20-period, 2 std)
    - RSI(14) < 25

    Entry trigger:
    - Volume climax: today's volume > 200% of 20-day average
    - Bullish reversal candle: close > open (green candle)
    - Close > previous close (higher daily close)

    Priority: 1 (lowest)
    Allowed regimes: ALL (designed for crashes)
    """

    name = "buying_on_weakness"
    priority = 1

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        # B.O.W. fires in any regime — no gate check
        if not regime.allows_engine(self.name):
            return None

        if len(df) < max(BOW_BOLLINGER_PERIOD + 5, 30):
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        last_open = float(last["Open"])
        prev_close = float(prev["Close"])

        # Adaptive thresholds
        rsi_threshold = profile.rsi_oversold if profile else BOW_RSI_THRESHOLD
        vol_climax_ratio = profile.volume_spike_threshold if profile else BOW_VOLUME_CLIMAX_RATIO

        # ── Capitulation Check ────────────────────────────────────────
        rsi_series = rsi(df["Close"], period=14)
        prev_rsi = float(rsi_series.iloc[-2]) if not pd.isna(rsi_series.iloc[-2]) else 50.0

        upper_bb, middle_bb, lower_bb = bollinger_bands(
            df["Close"], period=BOW_BOLLINGER_PERIOD, num_std=BOW_BOLLINGER_STD
        )
        prev_lower_bb = float(lower_bb.iloc[-2]) if not pd.isna(lower_bb.iloc[-2]) else 0.0

        # Condition 1: Extreme RSI (adaptive)
        capitulation_rsi = prev_rsi < rsi_threshold
        
        # Condition 2: Bollinger Band Capitulation
        capitulation_bb = prev_close < prev_lower_bb

        # Condition 3: StochRSI Oversold Bounce
        stoch_k, stoch_d = stoch_rsi(df["Close"], period=BOW_STOCH_RSI_PERIOD)
        prev_k = float(stoch_k.iloc[-2]) if not pd.isna(stoch_k.iloc[-2]) else 50.0
        prev_d = float(stoch_d.iloc[-2]) if not pd.isna(stoch_d.iloc[-2]) else 50.0
        last_k = float(stoch_k.iloc[-1]) if not pd.isna(stoch_k.iloc[-1]) else 50.0
        last_d = float(stoch_d.iloc[-1]) if not pd.isna(stoch_d.iloc[-1]) else 50.0
        
        capitulation_stoch = (
            prev_k < BOW_STOCH_RSI_OVERSOLD and 
            prev_d < BOW_STOCH_RSI_OVERSOLD and 
            last_k > last_d and  # Bullish cross today
            prev_k <= prev_d     # Was below or equal yesterday
        )

        # Condition 4: MACD Bullish Divergence
        macd_line, signal_line, macd_hist = macd(
            df["Close"], fast=BOW_MACD_FAST, slow=BOW_MACD_SLOW, signal=BOW_MACD_SIGNAL
        )
        
        capitulation_macd = False
        if len(df) > BOW_MACD_DIVERGENCE_LOOKBACK + 5:
            # Lookback window for price and MACD histogram
            lookback_lows = df["Low"].iloc[-(BOW_MACD_DIVERGENCE_LOOKBACK+1):-1]
            lookback_hists = macd_hist.iloc[-(BOW_MACD_DIVERGENCE_LOOKBACK+1):-1]
            
            min_low_idx = lookback_lows.idxmin()
            min_low_val = lookback_lows.min()
            
            # If price made a lower low recently compared to the N-day window
            if prev["Low"] <= min_low_val:
                # Find the histogram value at that previous absolute low
                hist_at_min_low = macd_hist.loc[min_low_idx]
                prev_hist = macd_hist.iloc[-2]
                
                # Divergence: Price is lower/equal, but Histogram is higher (less negative)
                if prev_hist < 0 and prev_hist > hist_at_min_low:
                    capitulation_macd = True

        if not (capitulation_rsi or capitulation_bb or capitulation_stoch or capitulation_macd):
            return None

        # ── Entry Trigger ─────────────────────────────────────────────
        # Volume climax today
        vol_ratio_series = volume_ratio(df, period=20)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < vol_climax_ratio:
            return None

        # Bullish reversal candle: close > open AND close > prev close
        if not (last_close > last_open and last_close > prev_close):
            return None

        # Signal confirmed
        last_rsi = float(rsi_series.iloc[-1]) if not pd.isna(rsi_series.iloc[-1]) else 50.0
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        # Score B.O.W. signals by volume intensity
        score = self.priority * last_vol_ratio

        capitulation_reason = []
        if capitulation_rsi:
            capitulation_reason.append(f"RSI={prev_rsi:.1f}<{rsi_threshold}")
        if capitulation_bb:
            capitulation_reason.append(f"below_lower_BB={prev_lower_bb:.0f}")
        if capitulation_stoch:
            capitulation_reason.append("StochRSI_Cross")
        if capitulation_macd:
            capitulation_reason.append("MACD_Div")

        details = {
            "capitulation": " + ".join(capitulation_reason),
            "prev_rsi": round(prev_rsi, 2),
            "current_rsi": round(last_rsi, 2),
            "volume_ratio": round(last_vol_ratio, 2),
            "prev_close": round(prev_close, 2),
            "lower_bb": round(prev_lower_bb, 2),
            "atr": round(last_atr, 2),
        }
        
        if capitulation_stoch:
            details["stoch_k"] = round(last_k, 2)
            details["stoch_d"] = round(last_d, 2)
            
        if capitulation_macd:
            details["macd_hist"] = round(float(macd_hist.iloc[-1]), 4)

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details=details,
        )


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 4: WYCKOFF PHASE C SPRING
# ══════════════════════════════════════════════════════════════════════════════


class WyckoffSpringEngine(BaseEngine):
    """
    Wyckoff Phase C Spring Entry Engine.

    Identifies a false breakdown (spring) below a 60-day trading range low.
    Triggers a buy ONLY when the daily low sweeps strictly below the 60-day minimum,
    but the daily close recovers above that minimum line on climax volume.

    Priority: 1
    Allowed regimes: CAUTION (Mean-Reverting)
    """

    name = "wyckoff_spring"
    priority = 1

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        if not regime.allows_engine(self.name):
            return None

        if len(df) < WYCKOFF_SPRING_LOOKBACK + 5:
            return None

        last = df.iloc[-1]
        last_low = float(last["Low"])
        last_close = float(last["Close"])

        # Lookback window BEFORE today
        lookback = df.iloc[-(WYCKOFF_SPRING_LOOKBACK + 1):-1]
        
        if len(lookback) < WYCKOFF_SPRING_LOOKBACK:
            return None

        min_60d = float(lookback["Low"].min())

        # 1. Sweep strictly below 60-day minimum
        if last_low >= min_60d:
            return None

        # 2. Close recovers above 60-day minimum
        if last_close <= min_60d:
            return None

        # 3. Climax volume (> 200% average)
        vol_ratio_series = volume_ratio(df, period=20)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < WYCKOFF_SPRING_VOLUME_RATIO:
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        score = self.priority * last_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "lookback_days": WYCKOFF_SPRING_LOOKBACK,
                "range_low": round(min_60d, 2),
                "sweep_low": round(last_low, 2),
                "sweep_depth_pct": round(((min_60d - last_low) / min_60d) * 100, 2),
                "volume_ratio": round(last_vol_ratio, 2),
                "atr": round(last_atr, 2),
            },
        )



# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 5: VOLUME CLIMAX REVERSAL
# ══════════════════════════════════════════════════════════════════════════════


class VolumeClimaxReversalEngine(BaseEngine):
    """
    Volume Climax Reversal Entry Engine.

    Identifies extreme volume exhaustion events where a massive volume spike
    (>300% of 20-day average) occurs with a bearish wide-range candle
    (Closing Range < 0.25), suggesting selling climax exhaustion.

    The entry triggers when today's price action confirms demand absorption:
    close > previous close AND close > open (bullish candle).

    Conditions:
    1. Previous day: Volume > 300% of 20-day average (climax volume)
    2. Previous day: Closing Range < 0.25 (closed near the low)
    3. Previous day: Body size > 1.5% of price (real move, not a doji)
    4. Today: Close > Previous Close AND Close > Open (bullish reversal)

    Priority: 2
    Allowed regimes: BULL, CAUTION
    """

    name = "volume_climax_reversal"
    priority = 2

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        if not regime.allows_engine(self.name):
            return None

        if len(df) < 25:
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        last_open = float(last["Open"])
        prev_close = float(prev["Close"])
        prev_open = float(prev["Open"])
        prev_high = float(prev["High"])
        prev_low = float(prev["Low"])

        # Adaptive threshold for volume climax
        vclr_vol_ratio = VCLR_VOLUME_RATIO
        if profile:
            vclr_vol_ratio = max(2.0, profile.volume_spike_threshold * 1.2)

        # 1. Previous day volume climax (> adaptive threshold)
        vol_ratio_series = volume_ratio(df, period=20)
        prev_vol_ratio = float(vol_ratio_series.iloc[-2]) if not pd.isna(vol_ratio_series.iloc[-2]) else 1.0

        if prev_vol_ratio < vclr_vol_ratio:
            return None

        # 2. Previous day closing range < 0.25 (closed near the low = bearish exhaustion)
        cr_series = closing_range(df)
        prev_cr = float(cr_series.iloc[-2]) if not pd.isna(cr_series.iloc[-2]) else 0.5

        if prev_cr >= VCLR_CLOSING_RANGE_MAX:
            return None

        # 3. Previous day body size > 1.5% (real move, not a doji)
        body_pct = abs(prev_close - prev_open) / prev_close * 100.0
        if body_pct < VCLR_MIN_BODY_PCT:
            return None

        # 4. Today's reversal confirmation: close > prev_close AND close > open
        if not (last_close > prev_close and last_close > last_open):
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        score = self.priority * prev_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "climax_vol_ratio": round(prev_vol_ratio, 2),
                "climax_closing_range": round(prev_cr, 2),
                "climax_body_pct": round(body_pct, 2),
                "reversal_vol_ratio": round(last_vol_ratio, 2),
                "atr": round(last_atr, 2),
            },
        )


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 6: EMA CROSSOVER
# ══════════════════════════════════════════════════════════════════════════════


class EMACrossoverEngine(BaseEngine):
    """
    EMA Crossover Entry Engine.

    Identifies EMA(9) crossing above EMA(21) with volume and RSI confirmation.
    This is a more sensitive momentum signal designed to catch trend-following
    entries that the strict Momentum Breakout engine misses.

    Conditions:
    1. EMA(9) crossed above EMA(21) today (was below yesterday)
    2. Price is above SMA(50) — uptrend confirmation
    3. Volume >= adaptive threshold (default 120% of 20-day average)
    4. RSI between adaptive bounds (default 40-70)
    5. Close > Open (bullish candle)

    Priority: 2
    Allowed regimes: BULL, CAUTION
    """

    name = "ema_crossover"
    priority = 2

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        if not regime.allows_engine(self.name):
            return None

        if len(df) < max(REGIME_SMA_SHORT + 5, EMA_SLOW_PERIOD + 5):
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        last_open = float(last["Open"])

        # Adaptive thresholds
        if profile:
            adapted = {}
            adapted["rsi_min"] = max(30.0, profile.rsi_oversold + 5.0)
            adapted["rsi_max"] = min(80.0, profile.rsi_overbought - 5.0)
            adapted["vol_threshold"] = max(1.1, profile.volume_spike_threshold * 0.6)
        else:
            adapted = {
                "rsi_min": EMA_CROSSOVER_RSI_MIN,
                "rsi_max": EMA_CROSSOVER_RSI_MAX,
                "vol_threshold": EMA_CROSSOVER_VOLUME_THRESHOLD,
            }

        # 1. EMA crossover: EMA(9) crosses above EMA(21)
        ema_fast = ema(df["Close"], EMA_FAST_PERIOD)
        ema_slow = ema(df["Close"], EMA_SLOW_PERIOD)

        last_ema_fast = float(ema_fast.iloc[-1]) if not pd.isna(ema_fast.iloc[-1]) else 0
        last_ema_slow = float(ema_slow.iloc[-1]) if not pd.isna(ema_slow.iloc[-1]) else 0
        prev_ema_fast = float(ema_fast.iloc[-2]) if not pd.isna(ema_fast.iloc[-2]) else 0
        prev_ema_slow = float(ema_slow.iloc[-2]) if not pd.isna(ema_slow.iloc[-2]) else 0

        # Must have crossed today (was below/equal yesterday, above today)
        if not (prev_ema_fast <= prev_ema_slow and last_ema_fast > last_ema_slow):
            return None

        # 2. Uptrend check: price above SMA(50)
        sma50 = sma(df["Close"], REGIME_SMA_SHORT)
        if pd.isna(sma50.iloc[-1]) or last_close <= float(sma50.iloc[-1]):
            return None

        # 3. Volume confirmation
        vol_ratio_series = volume_ratio(df, period=20)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < adapted["vol_threshold"]:
            return None

        # 4. RSI in adaptive range (not overbought, not oversold)
        rsi_series = rsi(df["Close"], period=14)
        last_rsi = float(rsi_series.iloc[-1]) if not pd.isna(rsi_series.iloc[-1]) else 50.0

        if last_rsi < adapted["rsi_min"] or last_rsi > adapted["rsi_max"]:
            return None

        # 5. Bullish candle
        if last_close <= last_open:
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        score = self.priority * last_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "ema_fast": round(last_ema_fast, 2),
                "ema_slow": round(last_ema_slow, 2),
                "crossover_gap": round(last_ema_fast - last_ema_slow, 2),
                "rsi": round(last_rsi, 2),
                "volume_ratio": round(last_vol_ratio, 2),
                "sma50": round(float(sma50.iloc[-1]), 2),
                "atr": round(last_atr, 2),
                "adaptive": profile is not None,
            },
        )


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 7: QUICK SWING TRADE
# ══════════════════════════════════════════════════════════════════════════════


class QuickSwingTradeEngine(BaseEngine):
    """
    Quick Swing Trade Entry Engine.

    Targets short-duration momentum trades (2-5 day holds) by identifying
    stocks where short-term momentum is shifting bullish. Uses faster
    indicators than the other engines to catch quick swing opportunities.

    Conditions:
    1. RSI(7) crossed above 50 today (was <=50 yesterday) — momentum shift
    2. Price closed above EMA(10) AND was below EMA(10) yesterday — trend reclaim
    3. Volume >= 110% of 10-day average — participation confirms the move
    4. Close > Open — bullish candle (buyers in control)
    5. Price above SMA(50) — aligned with the larger uptrend

    Priority: 2
    Allowed regimes: BULL, CAUTION
    """

    name = "quick_swing_trade"
    priority = 2

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
        profile: "StockProfile | None" = None,
    ) -> EntrySignal | None:
        # Regime gate
        if not regime.allows_engine(self.name):
            return None

        if len(df) < max(REGIME_SMA_SHORT + 5, QST_EMA_PERIOD + 5, QST_RSI_PERIOD + 5):
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        last_open = float(last["Open"])
        prev_close = float(prev["Close"])

        # Adaptive thresholds
        vol_threshold = QST_VOLUME_THRESHOLD
        rsi_cross = QST_RSI_CROSS_LEVEL
        if profile:
            vol_threshold = max(1.0, profile.volume_spike_threshold * 0.5)

        # 1. RSI(7) momentum shift: crossed above 50 today
        rsi_series = rsi(df["Close"], period=QST_RSI_PERIOD)
        last_rsi = float(rsi_series.iloc[-1]) if not pd.isna(rsi_series.iloc[-1]) else 50.0
        prev_rsi = float(rsi_series.iloc[-2]) if not pd.isna(rsi_series.iloc[-2]) else 50.0

        if not (prev_rsi <= rsi_cross and last_rsi > rsi_cross):
            return None

        # 2. EMA(10) reclaim: closed above EMA(10) today, was below yesterday
        ema_fast = ema(df["Close"], QST_EMA_PERIOD)
        last_ema = float(ema_fast.iloc[-1]) if not pd.isna(ema_fast.iloc[-1]) else 0
        prev_ema = float(ema_fast.iloc[-2]) if not pd.isna(ema_fast.iloc[-2]) else 0

        if not (prev_close <= prev_ema and last_close > last_ema):
            return None

        # 3. Volume confirmation: >= adaptive threshold of 10-day average
        vol_ratio_series = volume_ratio(df, period=QST_VOLUME_LOOKBACK)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < vol_threshold:
            return None

        # 4. Bullish candle: close > open
        if last_close <= last_open:
            return None

        # 5. Trend filter: price above SMA(50)
        sma50 = sma(df["Close"], REGIME_SMA_SHORT)
        if pd.isna(sma50.iloc[-1]) or last_close <= float(sma50.iloc[-1]):
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        score = self.priority * last_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "rsi7_prev": round(prev_rsi, 2),
                "rsi7_now": round(last_rsi, 2),
                "ema10": round(last_ema, 2),
                "volume_ratio": round(last_vol_ratio, 2),
                "sma50": round(float(sma50.iloc[-1]), 2),
                "atr": round(last_atr, 2),
                "adaptive": profile is not None,
            },
        )


# ─── Engine Registry ─────────────────────────────────────────────────────────

from core.ml_engine import GradientBoostEngine
from core.deep_engine import LSTMDirectionEngine

# Ordered by priority (highest first) — this is the evaluation order
ALL_ENGINES: list[BaseEngine] = [
    GradientBoostEngine(),
    LSTMDirectionEngine(),
    FVGPullbackEngine(),
    MomentumBreakoutEngine(),
    EMACrossoverEngine(),
    QuickSwingTradeEngine(),
    BuyingOnWeaknessEngine(),
    WyckoffSpringEngine(),
    VolumeClimaxReversalEngine(),
]


def run_all_engines(
    df: pd.DataFrame,
    ticker: str,
    regime: RegimeSnapshot,
    profile: "StockProfile | None" = None,
) -> list[EntrySignal]:
    """
    Run all engines against a single stock and collect signals.

    Returns a list of all signals that fired (usually 0 or 1).
    Multiple engines can fire on the same stock.
    """
    signals: list[EntrySignal] = []
    for engine in ALL_ENGINES:
        try:
            signal = engine.scan(df, ticker, regime, profile=profile)
            if signal:
                signals.append(signal)
                logger.debug(
                    "[%s] Engine '%s' fired: %s",
                    ticker, engine.name, signal,
                )
        except Exception as e:
            logger.warning(
                "[%s] Engine '%s' error: %s", ticker, engine.name, e
            )
    return signals
